spring:
  application:
    name: bill-api-generator
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:35050/bill_generator
    username: postgres
    password: aaaaaa
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

# Puerto del servidor
server:
  port: 8080

# Logging
logging:
  level:
    com.bill_api_generator: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE